server:
  port: 8084

spring:
  application:
    name: code-service
  datasource:
    # docker-compose'daki POSTGRES_DB: code_analysis_db ile uyumlu olmalı
    url: jdbc:p6spy:postgresql://localhost:5432/code_analysis_db
    username: postgres
    # docker-compose'daki POSTGRES_PASSWORD: postgres_password ile uyumlu olmalı
    password: postgres_password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    redis:
      host: localhost
      port: 6379

rabbitmq:
  exchange: code-exchange
  queue: code.analysis.queue
  routingkey: code-routing-key
  result:
    queue: code.result.queue
    routingkey: code.result.routing-key

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    p6spy: DEBUG
